cmake_minimum_required(VERSION 3.19)
include("${PICO_SDK_PATH}/external/pico_sdk_import.cmake")
project(enroll C CXX ASM)
set(CMAKE_C_STANDARD 11)
pico_sdk_init()
add_executable(enroll main.c ../src/enroll.c ../src/r503.c ../src/uart.c)
target_include_directories(enroll PRIVATE ../src)
target_compile_options(enroll PRIVATE -Wall -Wextra -Werror)
target_link_libraries(enroll PRIVATE pico_stdlib hardware_uart pico_stdio_usb)
pico_enable_stdio_uart(enroll 0)
pico_enable_stdio_usb(enroll 1)
pico_add_extra_outputs(enroll)
